FROM ubuntu

# pull the official base image
FROM python:3.8
# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip 
RUN apt update
RUN apt install tk 
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
RUN apk add tk
# copy project
COPY . /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]