# Generated by Django 4.0.6 on 2022-08-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('hub_link', models.CharField(max_length=300)),
                ('phone', models.CharField(default='0', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image_link', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('currency_code', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.datahub')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datahub'),
        ),
    ]
